### ISSUE TITLE
Plugin brake Serveless commands when custom key is missing in serverless.yml

### ISSUE THREAD

**Issue by kagonzalez84** [nfour/serverless-build-plugin#14]
When you do not specify "custom" in your serverless.yml, all your serverless commands get broken.
For instance a simple help

> sls help
>   Type Error ---------------------------------------------
>      Cannot read property 'build' of undefined

**Comment by nfour** [comment]
Thanks for reporting.

The plugin will be getting some love over the next few weeks, leading up to parity with the latest serverless version. This should be an easy fix next week.
