### ISSUE TITLE
Unable to Deploy Single Function

### ISSUE THREAD

**Issue by rawphp** [nfour/serverless-build-plugin#17]
there is a bug in the build plugin where you cannot deploy single functions... after building the plugin is expected by serverless to send artifect paths back to serverless for all functions... but only the path for the function being deployed is sent back... hence it crashes with error

```
Error --------------------------------------------------
 
     No artifact path is set for function: "another-function"
```

**Comment by nfour** [comment]
Looking into this.

**Comment by nfour** [comment]
Looks like serverless@1.2 broke the hooks.

**Comment by nfour** [comment]
Let me know if this persists @rawphp
