### ISSUE TITLE
Warning in console output that no configuration was found

### ISSUE THREAD

**Issue by evanread** [nfour/serverless-build-plugin#26]
The build plugin works without configuration, assuming some default values.

This is usually undesirable I assume. Could the console output of the plugin be explicit about where it found configuration, or if it didn't find any?

**Comment by nfour** [comment]
It's one of those things where if you don't RTFM you're going to have unexplained behavior - you can't babysit people. It's why I don't document how to set up a serverless project or how to npm install the plugin.
