### ISSUE TITLE
the CLI produces the following error

### ISSUE THREAD

**Issue by jaronimo99** [nfour/serverless-build-plugin#27]
![screen shot 2017-02-07 at 1 37 53 pm](https://cloud.githubusercontent.com/assets/5075984/22710599/2239990e-ed3b-11e6-88f4-afc1d4946ba7.png)

**Comment by nfour** [comment]
You're not using serverless correctly, that is not a valid command.

https://serverless.com/framework/docs/providers/aws/cli-reference/
