### ISSUE TITLE
file build method requires .map files

### ISSUE THREAD

**Issue by JnJSW** [nfour/serverless-build-plugin#36]
The file build method currently requires .map files to be generated for each handler.  I found that surprising, as I'm not used to including map files in production builds.  

I got around this limitation by inserting the following into my webpack.config.js
`  devtool: 'source-map',`

**Comment by nfour** [comment]
Could you share details on your file build scenario? If a `.map` is `required`, as in, it errors without one, then that sounds like a bug.

The logic in merely checks if `${buildFilename}.map` exists and includes it in the bundle, if it does exist. If your webpack config specifies inline-source-maps or none at all, there probably shouldn't be a .map being generated anywhere.
