### ISSUE TITLE
Refactor 0.5 support and base plugin architecture

### ISSUE THREAD

**Issue by nfour** [nfour/serverless-build-plugin#9]
The 0.5 plugin currently duplicates code and can be assimilated.
- [x] Wait for #1 
- [ ] Create plugin-specific hooks in order to manipulate artifacts for 0.5

**Comment by onyxraven** [comment]
You've got a help wanted tag here and I'm wondering what you need help with?  I'm just starting to use multiple functions in lambda, but with varying packaging needs (mostly, excluding certain modules in some functions to keep size down) - so I'm looking for the excludes functionality that looks like it is in 0.5 but not in 'release'.

**Comment by nfour** [comment]
There is currently a but in both versions which fails to exclude nested dependencies in some scenarios.

As for the help wanted, this is mainly directed as @zyrorl but I will likely refactor 0.5 support in the coming days.

**Comment by nfour** [comment]
Deprecating 0.5 support - It should remain in its current state until 2.0
